beta_end = 0.018
bucket_no_upscale = true
bucket_reso_steps = 64
cache_latents = true
caption_extension = ".txt"
clip_skip = 1
dataset_config = "/lv0/kohya_ss_hydit/config_hydit_0.toml"
dynamo_backend = "no"
enable_bucket = true
epoch = 1
gradient_accumulation_steps = 1
huber_c = 0.1
huber_schedule = "snr"
learning_rate = 1e-5
learning_rate_te = 1e-5
loss_type = "l2"
lr_scheduler = "cosine"
lr_scheduler_args = []
lr_scheduler_num_cycles = 1
lr_scheduler_power = 1
lr_warmup_steps = 160
max_bucket_reso = 2048
max_data_loader_n_workers = 0
max_timestep = 1000
max_token_length = 75
max_train_steps = 1600
min_bucket_reso = 256
mixed_precision = "fp16"
multires_noise_discount = 0.3
noise_offset_type = "Original"
optimizer_type = "AdamW8bit"
output_name = "last"
pretrained_model_name_or_path = "/lv0/kohya_ss_hydit/models/HunyuanDiT-V1.2"
prior_loss_weight = 1
resolution = "1024,1024"
sample_prompts = "prompt.txt"
sample_sampler = "euler_a"
save_every_n_epochs = 1
save_every_n_steps = 50
save_model_as = "ckpt"
save_precision = "fp16"
train_batch_size = 1
train_data_dir = "/lv0/kohya_datasets/small_test_1k"
xformers = true
